# A Note on Python/Numpy Vectors

Broadcasting é uma facilidade na biblioteca Numpy pore, pode trazer algun efeitos indesejaveis na manipulacao de dados.

https://numpy.org/doc/stable/user/basics.broadcasting.html

https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm

In [1]:
import numpy as np

In [2]:
# armazenar cinco variaveis aleatorias gaussianas a matriz a
a=np.random.randn(5) 

In [3]:
print (a)

[-0.99614814  1.36886732  0.70886122  1.16681564 -0.3810899 ]


In [4]:
print (a.shape) #matriz de ordem 1 em Python


(5,)


**Isso nao é nem um vetor linha e tb não é um vetor coluna**

In [5]:
print(a.T) #para fazer a transposta

[-0.99614814  1.36886732  0.70886122  1.16681564 -0.3810899 ]


In [6]:
# vamos calcular o produto entre a e a sua transposta


print(np.dot(a, a.T))

4.875281341070462


# Este produto é errôneo: pois a resposta seria uma nova matriz ao invés de um némero inteiro.

O que devemos evitar é manipular dados na forma de a. Como **(5, )** isso dara margem para bugs.

Para correção deste problema, devemos escrever da seguinte forma abaixo:

In [8]:
a=np.random.randn(5,1)
a

array([[-1.20997522],
       [ 1.0182312 ],
       [-0.90772655],
       [ 0.12710108],
       [ 2.16279819]])

In [9]:
print(a.T)

[[-1.20997522  1.0182312  -0.90772655  0.12710108  2.16279819]]


**Veja a diferença!**

In [10]:
#Realizando a mesma multiplicação entre vetore

print(np.dot(a,a.T))

[[ 1.46404002 -1.23203452  1.09832663 -0.15378916 -2.6169322 ]
 [-1.23203452  1.03679478 -0.9242755   0.12941829  2.20222859]
 [ 1.09832663 -0.9242755   0.82396749 -0.11537303 -1.96322934]
 [-0.15378916  0.12941829 -0.11537303  0.01615469  0.27489399]
 [-2.6169322   2.20222859 -1.96322934  0.27489399  4.67769599]]


Por isso, o mesmo vale para o comando abaixo:

>a.shape=(5,)

o que nao tem comportamento consistente nem de linha e nem coluna. 
A recomendaçao seria 
>a.shape=(5,1)

**reshape** para definir a dimensao que se deseja.

**assert** ele checa a dimensao dos vetores.

In [12]:
#ficando da seguinte forma

assert(a.shape==(5,1))


>**Concluindo:**
>   
>    **Sempre use codigos do tipo (n,1) ou (1,n)**

What kind of array has dimensions in this format: (10, ) ? 

**A rank 1 array**
    
    